services:
  web-server-1:
    build:
      context: .
      dockerfile: web-server.Dockerfile
    container_name: docker-web-server-1
#    ports:
#      - "80:80"
#      - "8080:8080"
#      - "2222:22"
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=ANG_Panha-db
      - DB_USER=root
      - DB_PASS=Hello@123
    depends_on:
      - mysql
    networks:
      - devops-final
    volumes:
      - maven-shared-cache:/root/.m2/repository

  web-server-2:
    build:
      context: .
      dockerfile: web-server.Dockerfile
    container_name: docker-web-server-2
#    ports:
#      - "80:80"
#      - "8080:8080"
#      - "2222:22"
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=ANG_Panha-db
      - DB_USER=root
      - DB_PASS=Hello@123
    depends_on:
      - mysql
    networks:
      - devops-final
    volumes:
      - maven-shared-cache:/root/.m2/repository

  load-balancer:
    image: haproxy:alpine
    container_name: docker-load-balancer
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    ports:
      - "8090:8090"
      - "2222:22"
      - "1936:1936"
    depends_on:
      web-server-1:
        condition: service_started
      web-server-2:
        condition: service_started
    networks:
      - devops-final

  phpmyadmin:
    image: phpmyadmin:apache
    container_name: docker-phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ABSOLUTE_PATH: http://localhost:8090/phpmyadmin/
    depends_on:
      - mysql
    networks:
      - devops-final

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=ANG_Panha-db
      - MYSQL_ROOT_PASSWORD=Hello@123
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - mysql-backups:/app/backups
    networks:
      - devops-final

networks:
  devops-final:
    driver: bridge

volumes:
  mysql-data:
  mysql-backups:
  maven-shared-cache:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $HOME/.m2/repository
