[web_servers]
docker-web-server-1 ansible_connection=docker ansible_user=root
docker-web-server-2 ansible_connection=docker ansible_user=root
[databases]
docker-mysql-1 ansible_connection=docker ansible_user=root
